import type { Config } from 'tailwindcss'

export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface": "var(--color-surface)",
          "surface-container-high": "var(--color-surface-container-high)",
          "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
          "on-secondary": "var(--color-on-secondary)",
          "error-container": "var(--color-error-container)",
          "secondary": "var(--color-secondary)",
          "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
          "tertiary-container": "var(--color-tertiary-container)",
          "primary-fixed": "var(--color-primary-fixed)",
          "on-surface": "var(--color-on-surface)",
          "primary-container": "var(--color-primary-container)",
          "on-primary": "var(--color-on-primary)",
          "primary": "var(--color-primary)",
          "inverse-on-surface": "var(--color-inverse-on-surface)",
          "surface-container-highest": "var(--color-surface-container-highest)",
          "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
          "on-error": "var(--color-on-error)",
          "inverse-surface": "var(--color-inverse-surface)",
          "outline-variant": "var(--color-outline-variant)",
          "on-error-container": "var(--color-on-error-container)",
          "background": "var(--color-background)",
          "surface-container-lowest": "var(--color-surface-container-lowest)",
          "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
          "on-tertiary-container": "var(--color-on-tertiary-container)",
          "secondary-fixed": "var(--color-secondary-fixed)",
          "tertiary": "var(--color-tertiary)",
          "on-surface-variant": "var(--color-on-surface-variant)",
          "error": "var(--color-error)",
          "tertiary-fixed": "var(--color-tertiary-fixed)",
          "secondary-container": "var(--color-secondary-container)",
          "surface-container-low": "var(--color-surface-container-low)",
          "on-background": "var(--color-on-background)",
          "surface-bright": "var(--color-surface-bright)",
          "primary-fixed-dim": "var(--color-primary-fixed-dim)",
          "surface-dim": "var(--color-surface-dim)",
          "outline": "var(--color-outline)",
          "on-primary-fixed": "var(--color-on-primary-fixed)",
          "on-secondary-container": "var(--color-on-secondary-container)",
          "surface-container": "var(--color-surface-container)",
          "surface-variant": "var(--color-surface-variant)",
          "surface-tint": "var(--color-surface-tint)",
          "on-tertiary": "var(--color-on-tertiary)",
          "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
          "on-secondary-fixed": "var(--color-on-secondary-fixed)",
          "inverse-primary": "var(--color-inverse-primary)",
          "secondary-fixed-dim": "var(--color-secondary-fixed-dim)"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "grid-margin": "24px",
          "stack-sm": "8px",
          "stack-md": "16px",
          "gutter": "20px",
          "stack-lg": "32px",
          "section-gap": "64px"
      },
      "fontFamily": {
          "headline-lg-mobile": ["\"Source Serif 4\""],
          "body-md": ["Work Sans"],
          "headline-md": ["\"Source Serif 4\""],
          "body-lg": ["Work Sans"],
          "display-lg": ["\"Source Serif 4\""],
          "label-sm": ["IBM Plex Sans"],
          "headline-lg": ["\"Source Serif 4\""],
          "label-bold": ["IBM Plex Sans"]
      },
      "fontSize": {
          "headline-lg-mobile": ["28px", {"lineHeight": "34px", "fontWeight": "700"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
          "display-lg": ["48px", {"lineHeight": "56px", "fontWeight": "700"}],
          "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
          "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
          "label-bold": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
} satisfies Config
