/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewslettersRouteImport } from './routes/newsletters'
import { Route as OpinionRouteImport } from './routes/opinion'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as VideoRouteImport } from './routes/video'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminArticlesRouteImport } from './routes/admin/articles'
import { Route as AdminDocsRouteImport } from './routes/admin/docs'
import { Route as AdminEditorialRouteImport } from './routes/admin/editorial'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminNewArticleRouteImport } from './routes/admin/new-article'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as ArticleArticleIdRouteImport } from './routes/article.$articleId'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersRoute = NewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionRoute = OpinionRouteImport.update({
  id: '/opinion',
  path: '/opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocsRoute = AdminDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorialRoute = AdminEditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewArticleRoute = AdminNewArticleRouteImport.update({
  id: '/new-article',
  path: '/new-article',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const ArticleArticleIdRoute = ArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/newsletters': typeof NewslettersRoute
  '/opinion': typeof OpinionRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/video': typeof VideoRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/new-article': typeof AdminNewArticleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/newsletters': typeof NewslettersRoute
  '/opinion': typeof OpinionRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/video': typeof VideoRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/new-article': typeof AdminNewArticleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/newsletters': typeof NewslettersRoute
  '/opinion': typeof OpinionRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-up': typeof SignUpRoute
  '/video': typeof VideoRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/new-article': typeof AdminNewArticleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/live'
    | '/login'
    | '/newsletters'
    | '/opinion'
    | '/profile'
    | '/search'
    | '/sign-up'
    | '/video'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/docs'
    | '/admin/editorial'
    | '/admin/media'
    | '/admin/new-article'
    | '/admin/settings'
    | '/admin/staff'
    | '/article/$articleId'
    | '/category/$categoryId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/live'
    | '/login'
    | '/newsletters'
    | '/opinion'
    | '/profile'
    | '/search'
    | '/sign-up'
    | '/video'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/docs'
    | '/admin/editorial'
    | '/admin/media'
    | '/admin/new-article'
    | '/admin/settings'
    | '/admin/staff'
    | '/article/$articleId'
    | '/category/$categoryId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/live'
    | '/login'
    | '/newsletters'
    | '/opinion'
    | '/profile'
    | '/search'
    | '/sign-up'
    | '/video'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/docs'
    | '/admin/editorial'
    | '/admin/media'
    | '/admin/new-article'
    | '/admin/settings'
    | '/admin/staff'
    | '/article/$articleId'
    | '/category/$categoryId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  NewslettersRoute: typeof NewslettersRoute
  OpinionRoute: typeof OpinionRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignUpRoute: typeof SignUpRoute
  VideoRoute: typeof VideoRoute
  ArticleArticleIdRoute: typeof ArticleArticleIdRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters': {
      id: '/newsletters'
      path: '/newsletters'
      fullPath: '/newsletters'
      preLoaderRoute: typeof NewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinion': {
      id: '/opinion'
      path: '/opinion'
      fullPath: '/opinion'
      preLoaderRoute: typeof OpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/docs': {
      id: '/admin/docs'
      path: '/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AdminDocsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editorial': {
      id: '/admin/editorial'
      path: '/editorial'
      fullPath: '/admin/editorial'
      preLoaderRoute: typeof AdminEditorialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new-article': {
      id: '/admin/new-article'
      path: '/new-article'
      fullPath: '/admin/new-article'
      preLoaderRoute: typeof AdminNewArticleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/article/$articleId': {
      id: '/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/article/$articleId'
      preLoaderRoute: typeof ArticleArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminDocsRoute: typeof AdminDocsRoute
  AdminEditorialRoute: typeof AdminEditorialRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNewArticleRoute: typeof AdminNewArticleRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminDocsRoute: AdminDocsRoute,
  AdminEditorialRoute: AdminEditorialRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNewArticleRoute: AdminNewArticleRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  NewslettersRoute: NewslettersRoute,
  OpinionRoute: OpinionRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignUpRoute: SignUpRoute,
  VideoRoute: VideoRoute,
  ArticleArticleIdRoute: ArticleArticleIdRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
